<?php


/**
 * Skeleton subclass for performing query and update operations on the 'action_type' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Aug 14 06:44:35 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ActionTypePeer extends BaseActionTypePeer {

} // ActionTypePeer
