# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  # Name of application
  app_name: SwinEstate
  # Amount of items for pagination
  items_on_page: 5
  # Cost of the adds
  daily_ad_cost: 25.00
  # from address in any emails sent from this website
  from_email: info@swinestate.com
