# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: listing, action: index }

rent_homepage:
  url:   /
  param: { module: listing, action: index }

about:
  url:   /
  param: { module: listing, action: index }

contact:
  url:   /
  param: { module: listing, action: index }

sale_search:
  url: /sale/search
  param: { module: listing, action: search }

view_single:
  url: /view/:id
  param: {module: listing, action: view }
  requirements: { id: \d+ }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

register:
  url: /user/register
  param: { module: user, action: details }

alter_user:
  url: /user/details
  param: { module: user, action: details }

alter_alert:
  url: /user/alert/new
  param: { module: user, action: alterAlert }

create_sale_listing:
  url: /sale/new
  param: { module: listing, action: alterListing }

edit_sale_listing:
  url: /sale/edit/:id
  param: { module: listing, action: alterListing }
  requirements: { id: \d+ }

change_password:
  url: /user/password
  param: { module: user, action: changePassword }

profile_page:
  url: /user/profile
  param: { module: user, action: profile }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
