generator:
  class: sfPropelGenerator
  param:
    model_class:           Listing
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              Listing
    plural:                Listings
    route_prefix:          listing
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        max_per_page: 15
        display: [id, =name, bedrooms, bathrooms, car_spaces, created_at, updated_at]
      filter:  ~
      form:  
        class: ListingAdminForm
      edit:    ~
      new:     ~
