<?php


/**
 * Skeleton subclass for representing a row from the 'address' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Aug 23 12:32:41 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Address extends BaseAddress {

    public function  __toString() {

//        $address = '';
//
//        // when there is a unit number, put that in the object string value
//        if (isset($this->getUnitNumber()) || $this->getUnitNumber() != '') {
//            $address .= $this->getUnitNumber().'/';
//        }
//
//        // build rest of address
//        $address .= $this->getStreetNumber().' '.$this->getStreetName().', '.$this->getSuburb()->getName().' '.$this->getSuburb()->getPostcode().' '.$this->getSuburb()->getState();

        return $this->getStreetName();

    }

} // Address
