<?php


/**
 * Skeleton subclass for representing a row from the 'alert_property_type' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Oct  6 19:29:40 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AlertPropertyType extends BaseAlertPropertyType {

    /**
     * AlertPropertyType::__toString()
     * 
     * @return
     */
    public function  __toString() {

        return $this->getPropertyType()->getName();

    }

} // AlertPropertyType
