<?php

/**
 * Skeleton subclass for representing a row from the 'alert' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Aug 23 12:32:41 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Alert extends BaseAlert {

    /**
     * Alert::save()
     * 
     * @param mixed $con
     * @return
     */
    public function save(PropelPDO $con = null) {

        // if this is the first save attach the user id
        if ($this->isNew()) {
            try {
                $this->setUserId(sfContext::getInstance()->getUser()->getGuardUser()->getId());
            } catch (Exception $ex) {
                // if there is an exception a user isnt logged in, so throw a 401 unauthorised exception.
                throw new sfException('You are not authorised to save an Alert', 401);
            }
        }

        // call the parent to save
        $object = parent::save($con);

        return $object;
    }

}

// Alert
