<?php


/**
 * Skeleton subclass for performing query and update operations on the 'alert_property_type' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Oct  6 19:29:40 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AlertPropertyTypePeer extends BaseAlertPropertyTypePeer {

} // AlertPropertyTypePeer
