<?php


/**
 * Skeleton subclass for performing query and update operations on the 'interest' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Sep  2 11:47:26 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class InterestPeer extends BaseInterestPeer {

    // function to check if a user has any interests
    /**
     * InterestPeer::hasInterests()
     * 
     * @return
     */
    public static function hasInterests() {

        $c = new Criteria();

        $c->add(InterestPeer::USER_ID, sfContext::getInstance()->getUser()->getGuardUser()->getId());

        $count = InterestPeer::doCount($c);

        if ($count > 0) {

            return true;

        }

        return false;

    }

} // InterestPeer
