<?php


/**
 * Skeleton subclass for representing a row from the 'interest' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Sep  2 11:47:26 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Interest extends BaseInterest {

    public function getUserEmailForInterest() {

        // retrieve by the user_id which isnt the primary key!
        $c = new Criteria();
        $c->add(sfGuardUserProfilePeer::USER_ID, $this->getUserId());
        
        return sfGuardUserProfilePeer::doSelectOne($c)->getEmailAddress();

    }

    public function getUserNameForInterest() {

        return sfGuardUserPeer::retrieveByPK($this->getUserId())->getUsername();

    }

} // Interest
