<?php


/**
 * Skeleton subclass for performing query and update operations on the 'listing_type' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Aug 19 09:43:51 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ListingTypePeer extends BaseListingTypePeer {

} // ListingTypePeer
