<?php


/**
 * Skeleton subclass for performing query and update operations on the 'listing_time' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Aug 27 01:50:36 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ListingTimePeer extends BaseListingTimePeer {

} // ListingTimePeer
