<?php


/**
 * Skeleton subclass for performing query and update operations on the 'listing_type' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Aug 23 12:32:41 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ListingTypePeer extends BaseListingTypePeer {

    public static function getIdFromName($name) {

        // build the criteria for SQL
        $c = new Criteria();
        // get the item where the name = the parameter
        $c->add(self::NAME, $name);

        // return the id of the selected DB object
        return self::doSelectOne($c)->getId();

    }

} // ListingTypePeer
