<?php


/**
 * Skeleton subclass for performing query and update operations on the 'listing' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Aug 19 09:43:51 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ListingPeer extends BaseListingPeer {

    public static function getUsersActiveListings($user_id) {

        $c = new Criteria();
        $c->addJoin(ListingPeer::LISTING_STATUS_ID, ListingStatusPeer::ID);
        $c->add(ListingStatusPeer::NAME, 'Active');
        $c->add(ListingPeer::USER_ID, $user_id);

        return ListingPeer::doSelect($c);

    }


} // ListingPeer
