<?php


/**
 * Skeleton subclass for representing a row from the 'rent_details' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep  8 10:56:20 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class RentDetails extends BaseRentDetails {

    public function  __toString() {
        return '';
    }

} // RentDetails
