<?php


/**
 * Skeleton subclass for representing a row from the 'sale_details' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Sep  7 10:08:28 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SaleDetails extends BaseSaleDetails {

    /**
     * SaleDetails::__toString()
     * 
     * @return
     */
    public function  __toString() {
        return '';
    }

} // SaleDetails
