<?php

/**
 * Skeleton subclass for performing query and update operations on the 'suburb' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Aug 23 12:32:41 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SuburbPeer extends BaseSuburbPeer {

    public static function getSameSuburb($name, $postcode) {

        $c = new Criteria();

        $c->add(SuburbPeer::NAME, $name);
        $c->add(SuburbPeer::POSTCODE, $postcode);

        $suburb = SuburbPeer::doSelectOne($c);

//        if (empty($suburb)) {
//
//            return false;
//        }

        return $suburb;
    }

    public static function retrieveForAutoComplete($name, $limit) {

        $c = new Criteria();
        $c->add(SuburbPeer::NAME, $name . '%', Criteria::LIKE);

        $c->addAscendingOrderByColumn(SuburbPeer::NAME);

        $suburbs = array();
        foreach (SuburbPeer::doSelect($c) as $suburb) {
            $suburbs[$suburb->getId()] = (string) $suburb;
        }

        return $suburbs;
    }

}

// SuburbPeer
