generator:
  class: sfPropelGenerator
  param:
    model_class:           ListingTime
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ListingTime
    plural:                ListingTimes
    route_prefix:          listing_time
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~    
      list:    
        max_per_page: 15
        display: [id, =start_date, end_state, payment_status]
      filter:  ~
      form:    
        display: 
          Content: [start_date, end_date]
          Authorise: [payment_status]
      edit:    ~
      new:
        title: New Payment     
        display: 
          Content: [listing_id, start_date, end_date]
          Authorise: [payment_status, user_id]
          PaymentDetails: [payer_account_name, total_paid, payment_date]
