<?php

/**
 * Base class that represents a row from the 'listing_metadata_column' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Aug 27 06:01:58 2010
 *
 * @package    lib.model.om
 */
abstract class BaseListingMetadataColumn extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ListingMetadataColumnPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the listing_type_id field.
	 * @var        int
	 */
	protected $listing_type_id;

	/**
	 * The value for the code field.
	 * @var        string
	 */
	protected $code;

	/**
	 * The value for the label field.
	 * @var        string
	 */
	protected $label;

	/**
	 * The value for the value_type field.
	 * @var        string
	 */
	protected $value_type;

	/**
	 * The value for the required field.
	 * @var        boolean
	 */
	protected $required;

	/**
	 * The value for the min_length field.
	 * @var        int
	 */
	protected $min_length;

	/**
	 * The value for the max_length field.
	 * @var        int
	 */
	protected $max_length;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        ListingType
	 */
	protected $aListingType;

	/**
	 * @var        array ListingMetadataValue[] Collection to store aggregation of ListingMetadataValue objects.
	 */
	protected $collListingMetadataValues;

	/**
	 * @var        Criteria The criteria used to select the current contents of collListingMetadataValues.
	 */
	private $lastListingMetadataValueCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'ListingMetadataColumnPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [listing_type_id] column value.
	 * 
	 * @return     int
	 */
	public function getListingTypeId()
	{
		return $this->listing_type_id;
	}

	/**
	 * Get the [code] column value.
	 * 
	 * @return     string
	 */
	public function getCode()
	{
		return $this->code;
	}

	/**
	 * Get the [label] column value.
	 * 
	 * @return     string
	 */
	public function getLabel()
	{
		return $this->label;
	}

	/**
	 * Get the [value_type] column value.
	 * 
	 * @return     string
	 */
	public function getValueType()
	{
		return $this->value_type;
	}

	/**
	 * Get the [required] column value.
	 * 
	 * @return     boolean
	 */
	public function getRequired()
	{
		return $this->required;
	}

	/**
	 * Get the [min_length] column value.
	 * 
	 * @return     int
	 */
	public function getMinLength()
	{
		return $this->min_length;
	}

	/**
	 * Get the [max_length] column value.
	 * 
	 * @return     int
	 */
	public function getMaxLength()
	{
		return $this->max_length;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     ListingMetadataColumn The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ListingMetadataColumnPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [listing_type_id] column.
	 * 
	 * @param      int $v new value
	 * @return     ListingMetadataColumn The current object (for fluent API support)
	 */
	public function setListingTypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->listing_type_id !== $v) {
			$this->listing_type_id = $v;
			$this->modifiedColumns[] = ListingMetadataColumnPeer::LISTING_TYPE_ID;
		}

		if ($this->aListingType !== null && $this->aListingType->getId() !== $v) {
			$this->aListingType = null;
		}

		return $this;
	} // setListingTypeId()

	/**
	 * Set the value of [code] column.
	 * 
	 * @param      string $v new value
	 * @return     ListingMetadataColumn The current object (for fluent API support)
	 */
	public function setCode($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->code !== $v) {
			$this->code = $v;
			$this->modifiedColumns[] = ListingMetadataColumnPeer::CODE;
		}

		return $this;
	} // setCode()

	/**
	 * Set the value of [label] column.
	 * 
	 * @param      string $v new value
	 * @return     ListingMetadataColumn The current object (for fluent API support)
	 */
	public function setLabel($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->label !== $v) {
			$this->label = $v;
			$this->modifiedColumns[] = ListingMetadataColumnPeer::LABEL;
		}

		return $this;
	} // setLabel()

	/**
	 * Set the value of [value_type] column.
	 * 
	 * @param      string $v new value
	 * @return     ListingMetadataColumn The current object (for fluent API support)
	 */
	public function setValueType($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->value_type !== $v) {
			$this->value_type = $v;
			$this->modifiedColumns[] = ListingMetadataColumnPeer::VALUE_TYPE;
		}

		return $this;
	} // setValueType()

	/**
	 * Set the value of [required] column.
	 * 
	 * @param      boolean $v new value
	 * @return     ListingMetadataColumn The current object (for fluent API support)
	 */
	public function setRequired($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->required !== $v) {
			$this->required = $v;
			$this->modifiedColumns[] = ListingMetadataColumnPeer::REQUIRED;
		}

		return $this;
	} // setRequired()

	/**
	 * Set the value of [min_length] column.
	 * 
	 * @param      int $v new value
	 * @return     ListingMetadataColumn The current object (for fluent API support)
	 */
	public function setMinLength($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->min_length !== $v) {
			$this->min_length = $v;
			$this->modifiedColumns[] = ListingMetadataColumnPeer::MIN_LENGTH;
		}

		return $this;
	} // setMinLength()

	/**
	 * Set the value of [max_length] column.
	 * 
	 * @param      int $v new value
	 * @return     ListingMetadataColumn The current object (for fluent API support)
	 */
	public function setMaxLength($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->max_length !== $v) {
			$this->max_length = $v;
			$this->modifiedColumns[] = ListingMetadataColumnPeer::MAX_LENGTH;
		}

		return $this;
	} // setMaxLength()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     ListingMetadataColumn The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ListingMetadataColumnPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     ListingMetadataColumn The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ListingMetadataColumnPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->listing_type_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->code = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->label = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->value_type = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->required = ($row[$startcol + 5] !== null) ? (boolean) $row[$startcol + 5] : null;
			$this->min_length = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->max_length = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->created_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->updated_at = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = ListingMetadataColumnPeer::NUM_COLUMNS - ListingMetadataColumnPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating ListingMetadataColumn object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aListingType !== null && $this->listing_type_id !== $this->aListingType->getId()) {
			$this->aListingType = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ListingMetadataColumnPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ListingMetadataColumnPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aListingType = null;
			$this->collListingMetadataValues = null;
			$this->lastListingMetadataValueCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ListingMetadataColumnPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseListingMetadataColumn:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				ListingMetadataColumnPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseListingMetadataColumn:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ListingMetadataColumnPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseListingMetadataColumn:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(ListingMetadataColumnPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(ListingMetadataColumnPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseListingMetadataColumn:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				ListingMetadataColumnPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aListingType !== null) {
				if ($this->aListingType->isModified() || $this->aListingType->isNew()) {
					$affectedRows += $this->aListingType->save($con);
				}
				$this->setListingType($this->aListingType);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ListingMetadataColumnPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ListingMetadataColumnPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ListingMetadataColumnPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collListingMetadataValues !== null) {
				foreach ($this->collListingMetadataValues as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aListingType !== null) {
				if (!$this->aListingType->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aListingType->getValidationFailures());
				}
			}


			if (($retval = ListingMetadataColumnPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collListingMetadataValues !== null) {
					foreach ($this->collListingMetadataValues as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ListingMetadataColumnPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getListingTypeId();
				break;
			case 2:
				return $this->getCode();
				break;
			case 3:
				return $this->getLabel();
				break;
			case 4:
				return $this->getValueType();
				break;
			case 5:
				return $this->getRequired();
				break;
			case 6:
				return $this->getMinLength();
				break;
			case 7:
				return $this->getMaxLength();
				break;
			case 8:
				return $this->getCreatedAt();
				break;
			case 9:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ListingMetadataColumnPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getListingTypeId(),
			$keys[2] => $this->getCode(),
			$keys[3] => $this->getLabel(),
			$keys[4] => $this->getValueType(),
			$keys[5] => $this->getRequired(),
			$keys[6] => $this->getMinLength(),
			$keys[7] => $this->getMaxLength(),
			$keys[8] => $this->getCreatedAt(),
			$keys[9] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ListingMetadataColumnPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setListingTypeId($value);
				break;
			case 2:
				$this->setCode($value);
				break;
			case 3:
				$this->setLabel($value);
				break;
			case 4:
				$this->setValueType($value);
				break;
			case 5:
				$this->setRequired($value);
				break;
			case 6:
				$this->setMinLength($value);
				break;
			case 7:
				$this->setMaxLength($value);
				break;
			case 8:
				$this->setCreatedAt($value);
				break;
			case 9:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ListingMetadataColumnPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setListingTypeId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCode($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setLabel($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setValueType($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setRequired($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setMinLength($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setMaxLength($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setCreatedAt($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setUpdatedAt($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ListingMetadataColumnPeer::DATABASE_NAME);

		if ($this->isColumnModified(ListingMetadataColumnPeer::ID)) $criteria->add(ListingMetadataColumnPeer::ID, $this->id);
		if ($this->isColumnModified(ListingMetadataColumnPeer::LISTING_TYPE_ID)) $criteria->add(ListingMetadataColumnPeer::LISTING_TYPE_ID, $this->listing_type_id);
		if ($this->isColumnModified(ListingMetadataColumnPeer::CODE)) $criteria->add(ListingMetadataColumnPeer::CODE, $this->code);
		if ($this->isColumnModified(ListingMetadataColumnPeer::LABEL)) $criteria->add(ListingMetadataColumnPeer::LABEL, $this->label);
		if ($this->isColumnModified(ListingMetadataColumnPeer::VALUE_TYPE)) $criteria->add(ListingMetadataColumnPeer::VALUE_TYPE, $this->value_type);
		if ($this->isColumnModified(ListingMetadataColumnPeer::REQUIRED)) $criteria->add(ListingMetadataColumnPeer::REQUIRED, $this->required);
		if ($this->isColumnModified(ListingMetadataColumnPeer::MIN_LENGTH)) $criteria->add(ListingMetadataColumnPeer::MIN_LENGTH, $this->min_length);
		if ($this->isColumnModified(ListingMetadataColumnPeer::MAX_LENGTH)) $criteria->add(ListingMetadataColumnPeer::MAX_LENGTH, $this->max_length);
		if ($this->isColumnModified(ListingMetadataColumnPeer::CREATED_AT)) $criteria->add(ListingMetadataColumnPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(ListingMetadataColumnPeer::UPDATED_AT)) $criteria->add(ListingMetadataColumnPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ListingMetadataColumnPeer::DATABASE_NAME);

		$criteria->add(ListingMetadataColumnPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of ListingMetadataColumn (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setListingTypeId($this->listing_type_id);

		$copyObj->setCode($this->code);

		$copyObj->setLabel($this->label);

		$copyObj->setValueType($this->value_type);

		$copyObj->setRequired($this->required);

		$copyObj->setMinLength($this->min_length);

		$copyObj->setMaxLength($this->max_length);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getListingMetadataValues() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addListingMetadataValue($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     ListingMetadataColumn Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ListingMetadataColumnPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ListingMetadataColumnPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a ListingType object.
	 *
	 * @param      ListingType $v
	 * @return     ListingMetadataColumn The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setListingType(ListingType $v = null)
	{
		if ($v === null) {
			$this->setListingTypeId(NULL);
		} else {
			$this->setListingTypeId($v->getId());
		}

		$this->aListingType = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the ListingType object, it will not be re-added.
		if ($v !== null) {
			$v->addListingMetadataColumn($this);
		}

		return $this;
	}


	/**
	 * Get the associated ListingType object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     ListingType The associated ListingType object.
	 * @throws     PropelException
	 */
	public function getListingType(PropelPDO $con = null)
	{
		if ($this->aListingType === null && ($this->listing_type_id !== null)) {
			$this->aListingType = ListingTypePeer::retrieveByPk($this->listing_type_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aListingType->addListingMetadataColumns($this);
			 */
		}
		return $this->aListingType;
	}

	/**
	 * Clears out the collListingMetadataValues collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addListingMetadataValues()
	 */
	public function clearListingMetadataValues()
	{
		$this->collListingMetadataValues = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collListingMetadataValues collection (array).
	 *
	 * By default this just sets the collListingMetadataValues collection to an empty array (like clearcollListingMetadataValues());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initListingMetadataValues()
	{
		$this->collListingMetadataValues = array();
	}

	/**
	 * Gets an array of ListingMetadataValue objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this ListingMetadataColumn has previously been saved, it will retrieve
	 * related ListingMetadataValues from storage. If this ListingMetadataColumn is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ListingMetadataValue[]
	 * @throws     PropelException
	 */
	public function getListingMetadataValues($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ListingMetadataColumnPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collListingMetadataValues === null) {
			if ($this->isNew()) {
			   $this->collListingMetadataValues = array();
			} else {

				$criteria->add(ListingMetadataValuePeer::METADATA_COLUMN_ID, $this->id);

				ListingMetadataValuePeer::addSelectColumns($criteria);
				$this->collListingMetadataValues = ListingMetadataValuePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ListingMetadataValuePeer::METADATA_COLUMN_ID, $this->id);

				ListingMetadataValuePeer::addSelectColumns($criteria);
				if (!isset($this->lastListingMetadataValueCriteria) || !$this->lastListingMetadataValueCriteria->equals($criteria)) {
					$this->collListingMetadataValues = ListingMetadataValuePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastListingMetadataValueCriteria = $criteria;
		return $this->collListingMetadataValues;
	}

	/**
	 * Returns the number of related ListingMetadataValue objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ListingMetadataValue objects.
	 * @throws     PropelException
	 */
	public function countListingMetadataValues(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ListingMetadataColumnPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collListingMetadataValues === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ListingMetadataValuePeer::METADATA_COLUMN_ID, $this->id);

				$count = ListingMetadataValuePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ListingMetadataValuePeer::METADATA_COLUMN_ID, $this->id);

				if (!isset($this->lastListingMetadataValueCriteria) || !$this->lastListingMetadataValueCriteria->equals($criteria)) {
					$count = ListingMetadataValuePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collListingMetadataValues);
				}
			} else {
				$count = count($this->collListingMetadataValues);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ListingMetadataValue object to this object
	 * through the ListingMetadataValue foreign key attribute.
	 *
	 * @param      ListingMetadataValue $l ListingMetadataValue
	 * @return     void
	 * @throws     PropelException
	 */
	public function addListingMetadataValue(ListingMetadataValue $l)
	{
		if ($this->collListingMetadataValues === null) {
			$this->initListingMetadataValues();
		}
		if (!in_array($l, $this->collListingMetadataValues, true)) { // only add it if the **same** object is not already associated
			array_push($this->collListingMetadataValues, $l);
			$l->setListingMetadataColumn($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this ListingMetadataColumn is new, it will return
	 * an empty collection; or if this ListingMetadataColumn has previously
	 * been saved, it will retrieve related ListingMetadataValues from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in ListingMetadataColumn.
	 */
	public function getListingMetadataValuesJoinListing($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ListingMetadataColumnPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collListingMetadataValues === null) {
			if ($this->isNew()) {
				$this->collListingMetadataValues = array();
			} else {

				$criteria->add(ListingMetadataValuePeer::METADATA_COLUMN_ID, $this->id);

				$this->collListingMetadataValues = ListingMetadataValuePeer::doSelectJoinListing($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ListingMetadataValuePeer::METADATA_COLUMN_ID, $this->id);

			if (!isset($this->lastListingMetadataValueCriteria) || !$this->lastListingMetadataValueCriteria->equals($criteria)) {
				$this->collListingMetadataValues = ListingMetadataValuePeer::doSelectJoinListing($criteria, $con, $join_behavior);
			}
		}
		$this->lastListingMetadataValueCriteria = $criteria;

		return $this->collListingMetadataValues;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collListingMetadataValues) {
				foreach ((array) $this->collListingMetadataValues as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collListingMetadataValues = null;
			$this->aListingType = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseListingMetadataColumn:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseListingMetadataColumn::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseListingMetadataColumn
