<?php


/**
 * This class defines the structure of the 'listing' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Aug 20 10:06:34 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ListingTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ListingTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('listing');
		$this->setPhpName('Listing');
		$this->setClassname('Listing');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('LISTING_TYPE_ID', 'ListingTypeId', 'INTEGER', 'listing_type', 'ID', true, null, null);
		$this->addForeignKey('ACTION_TYPE_ID', 'ActionTypeId', 'INTEGER', 'action_type', 'ID', true, null, null);
		$this->addForeignKey('ADDRESS_ID', 'AddressId', 'INTEGER', 'address', 'ID', true, null, null);
		$this->addColumn('NAME', 'Name', 'VARCHAR', true, 255, null);
		$this->addColumn('DESCRIPTION', 'Description', 'VARCHAR', true, 2000, null);
		$this->addColumn('BEDROOMS', 'Bedrooms', 'INTEGER', false, null, null);
		$this->addColumn('BATHROOMS', 'Bathrooms', 'INTEGER', false, null, null);
		$this->addColumn('GARAGE', 'Garage', 'INTEGER', false, null, null);
		$this->addColumn('ASKING_PRICE', 'AskingPrice', 'DECIMAL', true, null, null);
		$this->addColumn('ACTUAL_PRICE', 'ActualPrice', 'DECIMAL', false, null, null);
		$this->addForeignKey('LISTING_STATUS_ID', 'ListingStatusId', 'INTEGER', 'listing_status', 'ID', true, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('ListingType', 'ListingType', RelationMap::MANY_TO_ONE, array('listing_type_id' => 'id', ), null, null);
    $this->addRelation('ActionType', 'ActionType', RelationMap::MANY_TO_ONE, array('action_type_id' => 'id', ), null, null);
    $this->addRelation('Address', 'Address', RelationMap::MANY_TO_ONE, array('address_id' => 'id', ), null, null);
    $this->addRelation('ListingStatus', 'ListingStatus', RelationMap::MANY_TO_ONE, array('listing_status_id' => 'id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // ListingTableMap
