propel:
  listing:
    id: ~
    user_id: { type: integer, required: true, foreignTable: sf_guard_user, foreignReference: id }
    listing_type_id: { type: integer, required: true, foreignTable: listing_type, foreignReference: id }
    property_type_id: { type: integer, required: true, foreignTable: property_type, foreignReference: id }
    listing_status_id: { type: integer, required: true, foreignTable: listing_status, foreignReference: id }
    address_id: { type: integer, required: true, foreignTable: address, foreignReference: id }
    name: { type: varchar(255), required: true }
    description: { type: longvarchar, required: true }
    bedrooms: { type: integer, default: 0 }
    bathrooms: { type: integer, default: 0 }
    car_spaces: { type: integer, default: 0 }
    created_at: ~
    updated_at: ~

  listing_type:
    id: ~
    name: { type: varchar(255), required: true }
    created_at: ~
    updated_at: ~

  property_type:
    id: ~
    name: { type: varchar(255), required: true }
    created_at: ~
    updated_at: ~

  listing_status:
    id: ~
    name: { type: varchar(255), required: true }
    created_at: ~
    updated_at: ~

  listing_metadata_column:
    id: ~
    listing_type_id: { type: integer, required: true, foreignTable: listing_type, foreignReference: id }
    code: { type: varchar(25), required: true }
    label: { type: varchar(255), required: true }
    value_type: { type: varchar(10), required: true }
    required: boolean
    min_length: integer
    max_length: integer
    created_at: ~
    updated_at: ~

  listing_metadata_value:
    id: ~
    metadata_column_id: { type: integer, required: true, foreignTable: listing_metadata_column, foreignReference: id }
    listing_id: { type: integer, required: true, foreignTable: listing, foreignReference: id }
    value: { type: varchar(2000), required: true }
    created_at: ~
    updated_at: ~

  address:
    id: ~
    suburb_id: { type: integer, required: true, foreignTable: suburb, foreignReference: id }
    unit_number: varchar(10)
    street_number: { type: varchar(10), required: true }
    street_name: { type: varchar(255), required: true }
    created_at: ~
    updated_at: ~

  suburb:
    id: ~
    name: { type: varchar(100), required: true }
    postcode: { type: integer, required: true }
    state: { type: varchar(3), required: true }
    country: { type: varchar(100), required: true }
    created_at: ~
    updated_at: ~

  listing_time:
    id: ~
    user_id: { type: integer, required: true, foreignTable: sf_guard_user, foreignReference: id }
    listing_id: { type: integer, required: true, foreignTable: listing, foreignReference: id }
    start_date: timestamp
    end_date: timestamp
    payment_status: {type: varchar(10), required: true }
    created_at: ~
    updated_at: ~

  listing_photos:
    id: ~
    listing_id: { type: integer, required: true, foreignTable: listing, foreignReference: id }
    path: { type: varchar(1000), required: true }
    caption: { type: varchar(500) }
    created_at: ~
    updated_at: ~

  listing_videos:
    id: ~
    listing_id: { type: integer, required: true, foreignTable: listing, foreignReference: id }
    url: { type: varchar(1000), required: true }
    caption: { type: varchar(500) }
    created_at: ~
    updated_at: ~

  user_profile:
    _attributes: { phpName: sfGuardUserProfile }
    id:
    user_id:     { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
    first_name:  varchar(50)
    last_name:   varchar(50)
    email_address: varchar(355)
    phone_number: varchar(20)
    created_at: ~
    updated_at: ~

  alert:
    id: ~
    user_id: { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
    name: { type: varchar(100), required: true }
    bedrooms: integer
    bathrooms: integer
    car_spaces: integer
    suburb: varchar(100)
    postcode: integer
    amount_alerted: { type: integer, default: 0 }
    active: boolean
    created_at: ~
    updated_at: ~